config/routes.rb
Rails.application.routes.draw do
  resources :productos
  resources :marcas

  get 'welcome/index'
  root 'productos#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marca.rb
class Marca < ApplicationRecord
    validates :brand, presence: true
    has_one :producto
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca ha sido creado' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
      
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca ha sido actualizado ' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca ha sido Eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:brand)
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
    @totalPrecios = Producto.sum("price")
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @marca = Marca.all
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:name, :brand, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductosMarcas</title>
    <%= csrf_meta_tags %>

    <!-- stylesheet rails -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- JS General -->
    <%= javascript_include_tag 'app', 'data-turbolinks-track': 'reload' %>
    
    
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link"><%= link_to '¡Yo quiero la chamba!' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link"><%= link_to 'Marcas', marcas_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link"><%= link_to 'Productos', productos_path %></a>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/marcas/_form.html.erb
<%= form_with(model: marca, local: true) do |form| %>
  <% if marca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
      <% marca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Marca %>
    <%= form.text_field :brand, id: :marca_brand, :required => true %>
  </div>
  </br>
  <%= form.submit :class => 'btn btn-primary', :onclick => "validateInptBrand();" %>
  

<% end %>

app/views/marcas/edit.html.erb
<div class="row">
    <div class="col">
    </div>
    <div class="col-md-4 col-md-offset-5">
    </br>
    </br>
<h1>Editar Marca</h1>

<%= render 'form', marca: @marca %>
    </br>
    </br>
    <ul class="inline">
      <li class="list-inline-item"><%= button_to "Ver", @marca, :class =>"btn btn-info", :method => :get %></li>|
      <li class="list-inline-item"><%= button_to "Regresar", marcas_path, :class =>"btn btn-warning", :method => :get %></li>
    </ul>

</div>

<div class="col">
</div>
</div>
</div>

app/views/marcas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marcas</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Marca</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.brand %></td>
        <td><%= link_to 'Ver', marca %></td>
        <td><%= link_to 'Editar', edit_marca_path(marca) %></td>
        <td><%= link_to 'Eliminar', marca, method: :delete, data: { confirm: '¿Estas seguro que deseas eliminar esta marca?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</br>
</br>

  <div class="row">
    <div class="col">
    </div>
    <div class="col">
      <%= button_to "Agregar Marca", new_marca_path, :class =>"btn btn-primary", :method => :get %>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/marcas/new.html.erb
</br>
</br>

<div class="row">
    <div class="col">
    </div>

    <div class="col">
        <h1>Nueva Marca</h1>
        <%= render 'form', marca: @marca %>
    </div>

    <div class="col">
    </div>
</div>
</div>

app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
    <div class="col">
    </div>
    <div class="col">
      <p>
        <strong>Marca:</strong>
        &nbsp;<%= @marca.brand %>
      </p>
    </div>
    <div class="col">
    </div>
  </div>
</div>


  <div class="row">
    <div class="col">
    </div>
    <div class="col">

    <ul class="inline">
      <li class="list-inline-item"><%= button_to "Editar", edit_marca_path(@marca), :class =>"btn btn-primary", :method => :get %></li>
      <li class="list-inline-item"><%= button_to "Atras", marcas_path , :class =>"btn btn-primary", :method => :get %></li>
    </ul>
    </div>
    <div class="col">
    </div>
  </div>
</div>

app/views/productos/_form.html.erb
<%= form_with(model: producto, local: true) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name, id: :producto_name, :required => true, :class => 'form-control' %>
  </div>

  <%= form.label :Marca %>

  <%= form.select :brand, options_from_collection_for_select(Marca.all, :brand, :brand), {include_blank: "-----------"}, {required: 'false', autofocus: 'true', class: 'form-control'}%>

  <div class="field">
    <%= form.label :Descripcion %>
    <%= form.text_field :description, id: :producto_description, :class => 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :Precio %>
    <%= form.number_field :price, id: :producto_price, :onkeyup => "validateInptPrice();", :class => 'form-control'  %>
  </div>

  </br>
  </br>

   <%= form.submit :class => "btn btn-primary", :onclick => "validateInptName();" %>
  

<% end %>

app/views/productos/edit.html.erb
<div class="row">
    <div class="col">
    </div>
    <div class="col-md-6 col-md-offset-5">
<h1>Editar Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Ver', @producto %> |
<%= link_to 'Atras', productos_path %>

 </div>
    <div class="col">
    </div>
</div>
</div>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="inline">
  <li class="list-inline-item"><h1>Productos</h1></li>
  <li class="list-inline-item"><h1>&nbsp;&nbsp;&nbsp;&nbsp;</h1></li>
  <li class="list-inline-item"><%= button_to 'Agregar Marca', new_marca_path, :class =>"btn btn-primary", :method => :get %></li>
  <li class="list-inline-item"><h1>&nbsp;&nbsp;&nbsp;&nbsp;</h1></li>
  <li class="list-inline-item"><%= button_to 'Nuevo Producto', new_producto_path, :class =>"btn btn-primary", :method => :get %></li>
</ul>
</br>
</br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Marca</th>
      <th>Descripcion</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.name %></td>
        <td><%= producto.brand %></td>
        <td><%= producto.description %></td>
        <td><%= producto.price %></td>
        <td><%= link_to 'Ver', producto %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Eliminar', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="2"></td>
      <td><strong>Total de los Precios:</strong></td>
       <td>
          <%= @totalPrecios %>
       </td>
    </tr>
  </tbody>
</table>

<br>

app/views/productos/new.html.erb
<div class="row">
    <div class="col">
    </div>
    <div class="col-md-6 col-md-offset-5">

<h1>Nuevo Producto</h1>
<%= render 'form', producto: @producto %>
</br>
</br>
<%= link_to 'Atras', productos_path %>

 </div>
    <div class="col">
    </div>
</div>
</div>

app/views/productos/show.html.erb
<div class="row">
  <div class="col-xs-6 col-md-4"></div>
  <div class="col-xs-6 col-md-4">
    </br>
    </br>
    </br>
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Name:</strong>
      <%= @producto.name %>
    </p>

    <p>
      <strong>Brand:</strong>
      <%= @producto.brand %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @producto.description %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @producto.price %>
    </p>


    <%= link_to 'Editar', edit_producto_path(@producto) %> |
    <%= link_to 'Atras', productos_path %>

  </div>
  <div class="col-xs-6 col-md-4"></div>
</div>